# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET build for iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Set bundle version
      run: sed -i.bak "s/{{CFBundleVersion}}/$(git rev-list 1.0..HEAD --count)/g" ./BlogMaui/Platforms/iOS/Info.plist
    - name: Import code-signing certificate
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-filepath: 'distribution.p12'
        p12-password: ${{ secrets.DISRIBUTION_P12_PASSWORD }}
    - name: Download Apple provisioning profile
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: 'com.qedcode.blogmaui'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install workloads
      run: dotnet workload restore
    - name: Copy production settings
      run: cp ./Settings/Settings.Production.cs ./BlogMaui/
    - name: Restore build and publish
      run: dotnet publish -f:net7.0-ios -c:Release /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false
    - name: Upload the .ipa artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: '**/*.ipa'
    - name: Upload app to TestFlight
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: ${{ github.workspace }}/BlogMaui/bin/Release/net7.0-ios/ios-arm64/publish/BlogMaui.ipa
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
